### ISSUE TITLE
Choosing the LICENSE

### ISSUE THREAD

**Issue by NobbZ** [exercism/erlang-analyzer#5]
When I initially created the first bunch of commits I blindly picked Apache 2.0 without any thinking.

In the meantime I remembered that most sub projects in exercism are MIT though.

Also as I am not a lawyer or do know much about the variety of licenses available, I just open this issue to let other people decide on the license.

@iHiD @kytrinyx I think you two are the most qualified people to do this decission.

**Comment by iHiD** [comment]
MIT please :)
